paths:
  /api/extend/products:
    get:
      summary: Obtiene todos los productos
      tags:
        - Productos
      responses:
        "200":
          description: Productos obtenidos con éxito
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        "404":
          description: No se encontraron productos
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Mensaje de error indicando que no se encontraron productos
    post:
      summary: Crear un nuevo producto 
      tags:
        - Productos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/NewProduct'
      responses:
        "200":
          description: Producto creado con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Mensaje de error indicando un error interno del servidor
  /api/extend/products/{id}:
    put:
      summary: Actualiza un producto existente
      tags:
        - Productos
      parameters:
        - in: path
          name: id
          required: true
          description: ID del producto que se desea actualizar
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        "200":
          description: Producto actualizado con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        "404":
          description: Producto no encontrado para actualizar
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Mensaje de error indicando que el producto no fue encontrado para actualizar
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Mensaje de error indicando un error interno del servidor
    delete:
      summary: Elimina un producto existente
      tags:
        - Productos
      parameters:
        - in: path
          name: id
          required: true
          description: ID del producto que se desea eliminar
          schema:
            type: string
      responses:
        "200":
          description: Producto eliminado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Mensaje indicando que el producto ha sido eliminado exitosamente
        "404":
          description: Producto no encontrado para eliminar
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Mensaje de error indicando que el producto no fue encontrado para eliminar
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Mensaje de error indicando un error interno del servidor

components:
  schemas:
    Product:
      type: object
      required:
        - _id
        - title
        - description
        - price
        - thumbnail
        - code
        - stock
      properties:
        _id:
          type: string
          description: Id autogenerada por la app
        title:
          type: string
          description: El nombre del producto
        description:
          type: string
          description: Descripción del producto
        price:
          type: number
          description: El precio del producto
        thumbnail:
          type: string
          description: La imagen del producto
        code:
          type: string
          description: El código del producto que será único
        stock:
          type: integer
          description: El stock del producto
      example:
        _id: "65fe272cfd0221f6c4fc20a8"
        title: "Nombre del producto"
        description: "Descripción del producto"
        price: 29.99
        thumbnail: "https://ejemplo.com/imagen-del-producto.jpg"
        code: "ABC123"
        stock: 50

  requestBodies:
    NewProduct:
      content:
        application/json:
          schema:
            type: object
            required:
              - title
              - description
              - price
              - thumbnail
              - code
              - stock
            properties:
              title:
                type: string
                description: El título del producto
              description:
                type: string
                description: Descripción del producto
              price:
                type: number
                description: El precio del producto
              thumbnail:
                type: string
                description: La imagen del producto
              code:
                type: string
                description: El código del producto que será único
              stock:
                type: integer
                description: El stock del producto
          example:
            title: "Nombre del producto"
